### ISSUE TITLE
cannot find start_training.launch

### ISSUE THREAD

**Issue by Superyoutiao** [prav2909/DoubleDQN_turtlebot2#1]
Hi, Prav! I saw your post "Double DQN on TurtleBot2(ROS), which is really easy to understand! However, I cannot find the start_training.launch file in this depository, would you please upload it?

**Comment by prav2909** [comment]
Hey,

Will upload and let you know.

Thanks
Praveen

**Comment by prav2909** [comment]
Just checked, you don't need it. Just follow the steps on my medium blog and it will work.

Blog: https://medium.com/analytics-vidhya/double-dqn-on-turtlebot-2-ros-91c289a5bda0

**Comment by Superyoutiao** [comment]
I think this launch file is needed(I'm new to ros)





---Original---
From: ***@***.***&gt;
Date: Wed, Jul 28, 2021 15:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [prav2909/DoubleDQN_turtlebot2] cannot find start_training.launch (#1)




 
Just checked, you don't need it. Just follow the steps on my medium blog and it will work.
 
Blog: https://medium.com/analytics-vidhya/double-dqn-on-turtlebot-2-ros-91c289a5bda0

**Comment by prav2909** [comment]
My bad ;)
Added the _start_training.launch_ now in the repository.
Thanks for noticing it.

**Comment by prav2909** [comment]
You will have to paste it inside /home/youruser/catkin_ws/src/fa_turtlebot/launch/

**Comment by Superyoutiao** [comment]
Thanks for your reply!!! However(please don't hate me, lol) I think the .ymal file is also missing, would you please check again?





---Original---
From: ***@***.***&gt;
Date: Wed, Jul 28, 2021 21:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [prav2909/DoubleDQN_turtlebot2] cannot find start_training.launch (#1)




 
You will have to paste it inside /home/youruser/catkin_ws/src/fa_turtlebot/launch/

**Comment by prav2909** [comment]
No problem.
will check and let you know.

**Comment by prav2909** [comment]
Uploaded

**Comment by Superyoutiao** [comment]
It finally works! Thank you! Starred already.&nbsp;

---Original---
From: ***@***.***&gt;
Date: Mon, Aug 2, 2021 00:07 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [prav2909/DoubleDQN_turtlebot2] cannot find start_training.launch (#1)




 
Uploaded

**Comment by prav2909** [comment]
Great, thanks.👍
